#situacoes usadas por categoria
#Tue Oct 06 13:17:27 BRT 2026
COMPARACAO_MEDIDAS=PO_COMPARACAO_MEDIDAS_dinheiro_1527166754
COMPOSICAO_MEDIDAS=PO_COMPOSICAO_MEDIDAS_bonecas_1023345945
COMPOSICAO_TRANSFORMACOES=PO_COMPOSICAO_TRANSFORMACAO_MEDIDAS_flores_422431114
TRANSFORMACAO_MEDIDAS=PO_TRANSFORMACAO_MEDIDAS_frutas_93128185
