#situacoes usadas por categoria
#Tue Sep 29 15:23:27 BRT 2026
COMPARACAO_MEDIDAS=PO_COMPARACAO_MEDIDAS_cds_1222854862
COMPOSICAO_MEDIDAS=PO_COMPOSICAO_MEDIDAS_figurinhas_755733109
COMPOSICAO_TRANSFORMACOES=PO_TRANSFORMACAO_COMPOSTA_DOIS_PASSOS_guloseimas_400916186
TRANSFORMACAO_MEDIDAS=PO_TRANSFORMACAO_MEDIDAS_frutas_93128185
