#situacoes usadas por categoria
#Tue Oct 06 11:54:18 BRT 2026
COMPARACAO_MEDIDAS=PO_COMPARACAO_MEDIDAS_dinheiro_667564143
COMPOSICAO_MEDIDAS=PO_COMPOSICAO_MEDIDAS_figurinhas_755733109
COMPOSICAO_TRANSFORMACOES=PO_TRANSFORMACAO_COMPOSTA_DOIS_PASSOS_chocolates_1269597383
TRANSFORMACAO_MEDIDAS=PO_TRANSFORMACAO_MEDIDAS_dinheiro_e_brinquedos_188709799
