

# Este arquivo de propriedades contem as mensagens de ajuda a serem exibidas para o
# usu\u00e1rio.

#Mensagens que indicam para o usuario o que ele tem que fazer

passo.1=<html>Escolha no menu a legenda correspondente \u00e0 categoria a qual pertence a situa\u00e7\u00e3o-problema</html>
passo.2= <html>Arraste o elemento do texto para o diagrama.</html>
passo.3= <html>Digite o resultado da quest\u00e3o, e tecle \"enter\".</html>
passo.4= <html>Parab\u00e9ns!!!! Podemos passar para proxima tarefa?</html>
passo.5= <html>Qual o sinal do n\u00famero relativo?</html>


#Mensagens apresentadas para o usuario a partir dos erros cometidos
# 1-Erros categorizacao podem ser
#   1.1 Composicao - quando o usuario seleciona o diagrama de composicao de medidas
#   1.2 Transforma\u00e7\u00e3o
#   1.3 Compara\u00e7\u00e3o
#   1.4 Multiplicacao
#   1.5 Divisao por partes
#   1.6 Divisao por cotas

erro.categorizacao.1 = <html>Na situa\u00e7\u00e3o-problema existem partes que formam um todo?</html>
erro.categorizacao.2 = <html>Na situa\u00e7\u00e3o-problema existe um conjunto inicial que se transforma num conjunto final?</html>
erro.categorizacao.3 = <html>Na situa\u00e7\u00e3o-problema existe um conjunto que est\u00e1 sendo comparado em rela\u00e7\u00e3o a outro conjunto?</html>
erro.categorizacao.4 = <html>Na situa\u00e7\u00e3o-problema o valor total \u00e9 desconhecido?</html>
erro.categorizacao.5 = <html>Na situa\u00e7\u00e3o-problema o valor de cada parte \u00e9 desconhecida?</html>
erro.categorizacao.6 = <html>Na situa\u00e7\u00e3o-problema o n\u00famero de partes \u00e9 desconhecida?</html>

#2-Erro posicionamento
erro.posicionamento = <html>Voc\u00ea tem certeza que o elemento foi posicionado corretamente?<br>Clique \"Ok\" para tentar novamente!</html>

#3-Erro de sinal
erro.sinal = <html>Tem certeza que o sinal est\u00e1 correto? Clique \"Ok\" para tentar novamente!</html>

#4-Erro de calculo do resultado
erro.calculo = <html>Valor incorreto! Leia a questao novamente e digite o resultado!</html>

#5-Mais dicas
maisdica.2 = <html>Observe os elementos selecionados no texto e arraste para o diagrama</html>
maisdica.3 = <html>Clique no elemento do diagrama onde voc\u00ea deseja digitar o valor.</html>

#6-Recomecar depois de tres erros consecutivos
recomecar = <html>Vamos recome\u00e7ar??.</html>
