# Este arquivo de propriedades contem as mensagens de aviso a serem exibidas para o
# usu\u00e1rio.

#<html>Nome: Smile<br> Idade: da pedra</html>
preencherCampos= Por favor, preencha todos os campos.
saudacao= Ol\u00e1 {0}, seja bem vind{1}!
fazerCadastro = <html> Usuario n\u00e3o cadastro.<br>Por favor, fa\u00e7a o seu cadastro!</html>
cadastroExiste = Usu\u00e1rio j\u00e1 possui cadastro!
senhaErrada= Senha inv\u00e1lida!

emailInvalido= Email inv\u00e1lido!
cpfInvalido= CPF inv\u00e1lido!
nomesInvalidos=  <html> Os campos \\"NOME DO USUARIO\\", \\"NOME DA ESCOLA\" e \\"CIDADE DA ESCOLA\\"<br>devem conter apenas letras. </html>
idadeInvalida= Idade inv\u00e1lida!

cidadeEscolaIvalido = <html>Nome da Cidade da Escola inv\u00e1lido!<br>Use apenas letras! </html>
nomeUsuarioIvalido = <html>Nome de Usu\u00e1rio inv\u00e1lido!<br>Use apenas letras! </html>
nomeEscolaIvalido = <html>Nome da Escola inv\u00e1lido!<br>Use apenas letras! </html>
senhaInvalida = Digite a senha com no m\u00ednimo 6 digitos!
senhasDiferentes = <html>As senhas informadas s\u00e3o diferentes!<br>Digite as senhas novamente!</html>

cadastroSucesso = Cadastro realizado com sucesso!!
cadastroFalha = <html>N\u00e3o foi poss\u00edvel realizar cadastro!<br>Falha no acesso ao banco!</html>

editarCadastroSucesso = Dados salvos com sucesso!!
editarCadastroFalha = <html>N\u00e3o foi poss\u00edvel salvar dados!<br>Falha no acesso ao banco!</html>

semHistorico = <html>Usu\u00e1rio ainda n\u00e3o possui hist\u00f3rico!.</html>
semMaisHistorico = <html>Sem mais hist\u00f3rico.</html>
semDadosBanco = <html>Nao existe Situa\u00e7\u00f5es Problemas no banco!<br>Por favor, feche o aplicativo e exclua o arquivo "Gerard.s3db".<br>Depois excute o programa novamente.</html>
problemasBase = <html>Nao foi possivel salvar estado!<br>Por favor, feche o aplicativo e exlua o arquivo "Gerard.s3db".<br>Depois excute o programa novamente.</html>
estadoSalvo = Estado salvo com sucesso!!
semEstadoSalvo =<html> Voce n\u00e3o possui estado salvo para este tipo de estruturas!!</html>