# Este arquivo de propriedades contem as mensagens a serem salvas no banco para produzir
# o historico de a\u00e7\u00f5es de cada usuario

ator.usuario = usu\u00e1rio
ator.computador = computador

descricao.clicou = usu\u00e1rio clicou no {0}
descricao.desenhaDiagrama = ({0} desenha diagrama de {1})
descricao.identificaElemento = ({0} identifca elemento)
#Ex: usuario arrasta elemento 9 para quadrado do referente
descricao.arrastaElemento = usu\u00e1rio arrasta elemento {0} para {1}
descricao.digita = usu\u00e1rio digita o valor {0}

#composicao
posicao.1.1= quadrado da parte da composi\u00e7\u00e3o
posicao.2.1= quadrado da parte da composi\u00e7\u00e3o
posicao.3.1= quadrado do todo da composi\u00e7\u00e3o

#transforma\u00e7\u00e3o
posicao.1.2=quadrado estado inicial
posicao.2.2=ciculo do n\u00famero relativo da transforma\u00e7\u00e3o
posicao.3.2=quadrado estado final

#compara\u00e7\u00e3o
posicao.1.3= quadrado do referente
posicao.2.3= circulo do n\u00famero relativo da compara\u00e7ao
posicao.3.3= quadrado do referido

#multiplicacao
posicao.1.4= quadrado 00
posicao.2.4= quadrado 01
posicao.3.4= quadrado 10
posicao.4.4= quadrado 11

#divis\u00e3o por partes

posicao.1.4= quadrado 10
posicao.2.4= quadrado 00
posicao.3.4= quadrado 11
posicao.4.4= quadrado 01

#divis\u00e3o por cotas
posicao.1.6= quadrado 00
posicao.2.6= quadrado 01
posicao.3.6= quadrado 10
posicao.4.6= quadrado 11


#artefatos de acordo com o que est\u00e1 salvo no banco
botao.1=Bot\u00e3o composi\u00e7\u00e3o
botao.2=Bot\u00e3o transforma\u00e7\u00e3o
botao.3=Bot\u00e3o compara\u00e7\u00e3o
botao.4=Bot\u00e3o mutiplicativa
botao.5=Bot\u00e3o divis\u00e3o por partes
botao.6=Bot\u00e3o divs\u00e3o por cotas
botao.refazer=Bot\u00e3o refazer
botao.maisdica=Bot\u00e3o mais dica
botao.sim=Bot\u00e3o sim
botao.nao=Botao n\u00e3o
botao.mais=Bot\u00e3o sinal de mais
botao.menos=Bot\u00e3o sinal de menos
botao.desfazer=Bot\u00e3o desfazer
janela.dialog=Janela de mensagem (JDialog)

historicoCabecalho = <b>PROBLEMA:</b>{0}<br><pre><b>CATEGORIA:</b> {1}  <b>TENTATIVA:</b> {2}    <b>Data:</b> {3}<br></pre><hr>
historico =<br><b>DESCRI\u00c7\u00c3O:</b>{0}<pre><<b>ATOR:</b> {1}    <b>VALOR:</b> {2}   <b>ERRO:</b> {3}</pre>