#Este arquivo contem as mensagens de ajuda exbidas para o aplicativo1

erro.pontoFinal = <html>N\u00e3o foi poss\u00edvel encontrar o Ponto final '.' indicando o fim da senten\u00e7a.</html>
erro.pontoInterrogacao = <html>N\u00e3o foi poss\u00edvel encontrar o s\u00edmbolo de interroga\u00e7\u00e3o '?' indicando o final da senten\u00e7a.</html>
erro.pronomes = <html>N\u00e3o foi poss\u00edvel encontrar os pronomes 'Quantos' ou 'Quantas'.</html>
erro.posicaoPerguntas = <html>A pergunta deve ser feita no final do enunciado, n\u00e3o antes.</html>
erro.perguntasSemPronome = <html>Pergunta sem os pronomes 'Quantos' ou 'Quantas'.</html>
erro.categoriaComposicao = <html>Voc\u00ea tem certeza que este problema \u00e9 de 'Composi\u00e7\u00e3o'?\n\nTente usar as palavras 'Juntos(as)', 'ao todo', 'em conjunto', etc.</html>
erro.termosComparativos = <html>Os termos comparativos utilizados indicam que o problema \u00e9 de 'Compara\u00e7\u00e3o' e n\u00e3o de 'Composi\u00e7\u00e3o'. Evite utilizar 'a mais', 'a menos', etc.</html>
erro.valoresErrados = <html>Os valores informados n\u00e3o est\u00e3o condizentes com o diagrama.</html>
erro.temposVerbais = <html>Os tempos verbais s\u00e3o diferentes e denotam ideia de quantidade inicial e final, incondizentes com o conceito de composi\u00e7\u00e3o.</html>
erro.objetosDiferentes = <html>Os objetos informados s\u00e3o diferentes!</html>
erro.verbosSemEquivalencia = <html>Os verbos informados n\u00e3o tem equival\u00eancia!</html>
erro.pessoasSemEquivalencia = <html>N\u00e3o foi poss\u00edvel achar uma correspond\u00eancia entre as pessoas do enunciado.</html>
parabens = <html>Parab\u00e9ns! O texto corresponde ao diagrama!</html>

erro.termosComparativosComparacaoT = <html>Os termos comparativos utilizados indicam que o problema \u00e9 de 'Compara\u00e7\u00e3o' e n\u00e3o de 'Transforma\u00e7\u00e3o'. Evite utilizar 'a mais', 'a menos', etc.</html>
erro.termosComposicaoT = <html>Os termos aglomerativos utilizados indicam que o problema \u00e9 de 'Composi\u00e7\u00e3o' e n\u00e3o de 'Transforma\u00e7\u00e3o'. Evite utilizar 'ao todo', 'juntos(as)', etc.</html>
erro.categoriaComparacao = <html>Voc\u00ea tem certeza que este problema \u00e9 de 'Compara\u00e7\u00e3o'?\n\nTente usar as palavras 'a mais que', 'a menos que', etc.</html>
erro.sinal = <html>O sinal da rela\u00e7\u00e3o n\u00e3o condiz com o termo comparativo utilizado.</html>
erro.referente = <html>As quantidades informadas n\u00e3o correspondem ao diagrama. Referente.</html>
erro.referido = <html>As quantidades informadas n\u00e3o correspondem ao diagrama. Referido.</html>
erro.relacaoC = <html>As quantidades informadas n\u00e3o correspondem ao diagrama. Rela\u00e7\u00e3o.</html>
erro.relacaoReferidoReferente = <html>A rela\u00e7\u00e3o entre o referido e o referente n\u00e3o est\u00e1 correta!</html>
erro.atoresSemEquivalencia = <html>N\u00e3o foi poss\u00edvel verificar a equival\u00eancia dos atores do enunciado!</html>
erro.malFormulada = <html>A pergunta n\u00e3o est\u00e1 bem formulada. Tente novamente!</html>



