# Este arquivo cont\u00e9m situa\u00e7\u00f5es problemas para quando o aplicativo for
#utilizado em modo Applet
#Eh possivel adicionar situa\u00e7\u00f5es-problemas, para isso \u00e9 necess\u00e1rio seguir o modelo

#SITUACAO_PROBLEMA = Questao#codCategoria#resposta#rotuloEsquerdo#rotuloDireito
#COMPONENTE = valor#codRepresentacao#sinal

#OBS= os codigos das categorias sao
#  COD   CATEGORIA
#   1    Composicao
#   2    Transforma\u00e7\u00e3o
#   3    Compara\u00e7\u00e3o
#   4    Multiplicacao
#   5    Divisao por partes
#   6    Divisao por cotas

#OBS= os codigos da representacao s\u00e3o
#  COD   REPRESENTACAO
#   0     quadrado
#   1     circulo

#OBS= as posicoes nos diagramas de estruturas aditivas s\u00e3o
#  POS   DIAGRAMA_COPOSICAO
#   1     parte_1
#   2     parte_2
#   3     todo

#  POS   DIAGRAMA_TRANSFORMACAO
#   1     estado_inicial
#   2     circulo
#   3     estado_final

#  POS   DIAGRAMA_COMPARACAO
#   1     referente
#   2     circulo
#   3     referido

#OBS= as posicoes nos diagramas multiplicativas s\u00e3o
#considerando os quadrados dos diagramas como se formassem uma matriz quadrada
#de ordem 2 temos:

#  POS      DIAGRAMA DE MULTIPLICACAO E DIVISAO POR COTAS      MATRIZ
#   1           a00                                            a00  a01
#   2           a01                                            a10  a11
#   3           a10
#   4           a11

#  POS      DIAGRAMA DE DIVISAO POR PARTES                      MATRIZ
#   2           a00                                            a00  a01
#   1           a10                                            a10  a11
#   4           a01
#   3           a11

#OBS: COMPONENTE.1 equivale ao componente localizado na posicao 1 do diagrama
#COMPONENTE.2 equivale ao componente localizado na posicao 2 do diagrama.. e assim por diante


#OBS = codigo para o sinal
#  COD    SINAL
#   +     sinal de mais
#   -     sinal de menos
#   s     sem sinal

#OBS= quando n\u00e3o existir rotulo (que fica em cima do diagrama) colocar letra s.
#Ex: MULTIPLICATIVAS.1 = maria..#

#Indique o numero de situacoes-problemas de estruturas aditivas existentes em NUMERO_ADITIVAS
NUMERO_ADITIVAS = 3

#Situacoes problemas do tipo aditiva
ADITIVAS.1 = Em uma festinha, existem 30 crian\u00e7as. Se apenas 7 crian\u00e7as est\u00e3o \
 sentadas, quantas crian\u00e7as est\u00e3o em p\u00e9?#1#23#s#s
COMPONENTE_A.1.1 =7#0#s
COMPONENTE_A.1.2 =?#0#s
COMPONENTE_A.1.3 =30#0#s

ADITIVAS.2 = Jo\u00e3o tinha 44 reais e n\u00e3o viu que seu bolso estava rasgado. \
Ao chegar em casa, Jo\u00e3o percebeu que s\u00f3 tinha 29 reais. Qual o valor da quantia \
perdida por Jo\u00e3o?#2#15#s#s
COMPONENTE_A.2.1 =44#0#s
COMPONENTE_A.2.2 =?#1#-
COMPONENTE_A.2.3 =29#0#s


ADITIVAS.3 = Julio tem 51 anos. Sua irm\u00e3 \u00e9 9 anos mais nova. Quantos anos, a irm\u00e3 \
de joao tem?#3#42#s#s
COMPONENTE_A.3.1 =51#0#s
COMPONENTE_A.3.2 =9#1#-
COMPONENTE_A.3.3 =?#0#s


#situa\u00e7\u00f5es problemas de estruturas multiplicativas
NUMERO_MULTIPLICATIVAS = 3

MULTIPLICATIVAS.1 = Para construir 3 casas, s\u00e3o necess\u00e1rios 6 pedreiros. Quantos \
pedreiros s\u00e3o necess\u00e1rios para construir 20 casas?#4#40#casas#pedreiros
COMPONENTE_M.1.1 =3#0#s
COMPONENTE_M.1.2 =6#0#s
COMPONENTE_M.1.3 =20#0#s
COMPONENTE_M.1.4 =?#0#s

MULTIPLICATIVAS.2 = Quantos quadros podem ser pintados se 30 artistas trabalharem, \
sabendo-se que para 3 quadros serem pintados s\u00e3o necess\u00e1rios 9 artistas?#6#10#quadros#artistas
COMPONENTE_M.2.1 =3#0#s
COMPONENTE_M.2.2 =9#0#s
COMPONENTE_M.2.3 =?#0#s
COMPONENTE_M.2.4 =22#0#s

MULTIPLICATIVAS.3 = Para consertar 7 carros, 21 mec\u00e2nicos precisam trabalhar. Se todos \
os carros s\u00e3o iguais, quantos mec\u00e2nicos s\u00e3o necess\u00e1rios para consertar somente 1 carro?#5#3#carros#mec\u00e2nicos
COMPONENTE_M.3.1 =7#0#s
COMPONENTE_M.3.2 =1#0#s
COMPONENTE_M.3.3 =21#0#s
COMPONENTE_M.3.4 =?#0#s



